### ISSUE TITLE
Get warning messages from CSVToXML converter into R

### ISSUE THREAD

**Issue by pralitp** [JGCRI/gcamdata#102]
Currently most of the error checking when converting CSV (or really tabular data) to XML is done in the Java CSVToXML tool.  Unfortunately the way we are calling this tool (using `pipe`) makes it impossible to capture the STDOUT/STDERR where the warning/error messages are printed thus unable to check them in the test cases.

We could get these messages if we switch to `system2` to call the Java tool however there is a steep performance penalty in using that instead of `pipe`.

**Comment by rplzzz** [comment]
Why the big performance penalty, I wonder.  They should be doing the same thing under the hood, just with slightly different options.  I wonder if the real performance difference comes because of capturing STDOUT and STDERR in the first place.  I'll bet R isn't particularly smart about how it does this when the command in question produces a lot of output.  

If that's what's happening, then we could probably do better by arranging to redirect STDOUT and STDERR to grep, which could filter for the stuff we're looking for and return only that to R for further processing.

Alternatively, you could give CSVtoXML an option that would cause it to write status relevant to another fd (i.e., not stdout or stderr), which could be connected back the calling program.

**Comment by pralitp** [comment]
Let me start with a disclaimer that it has been too long for me to remember all of the gory details but hopefully I've got enough for meaningful conversation.

Yes it has to do with how it is dealing with STDOUT/STDIN.  Particular to this case we are concerned about STDIN in as we are sending large amounts of data (for a number XML files at least) which is the tabular data to convert to XML.  CSVToXML will not be sending anything back via STDOUT (apart from error/warning messages) as it will write the XML to a file on disk.

`pipe` and `system` / `system2` are not the same under the hood.  They are just wrappers to the `C` function equivalents.  Thus `pipe` opens the process and feeds data as available.  However `system` will collect all of the data then launch the command.

That being said when I was testing `system2` and noticed the terrible performance I didn't full appreciate the documentation:

>    input: if a character vector is supplied, this is copied one string
>           per line to a temporary file, and the standard input of
>           'command' is redirected to the file.

I had `write.csv` write to a textConnection (to get it to a character vector) which was just getting written to a temporary file anyway.  I could have just set up the temporary file myself and this will likely alleviate some of the problem.  Although it still wouldn't be as fast as `pipe` as we would still have to go through disk.

The documentation for `pipe` is pretty scarce and it isn't totally clear that you shouldn't be able to redirect both input and output but after a lot of experimentation and googling it doesn't seem to work.  The output messages will get displayed on the R console but not in anyway that we can get the test code to recognize those messages.

> Alternatively, you could give CSVtoXML an option that would cause it to write status relevant to another fd (i.e., not stdout or stderr), which could be connected back the calling program.

Hmm, I guess I'm not sure how to do that.  Could you explain further?

**Comment by pralitp** [comment]
@rplzzz, @bpbond the priority level is elevated on this since apparently the call to `pipe` isn't working on Windows.  I'm going to go find a Windows machine to debug it but if `pipe` is the cause we'll have to but up the milestone on this issue.

**Comment by rplzzz** [comment]
I've done all I can do with the xml comparison scripts, so I could probably take on this matter next.  

Do we have access to Windows VMs on our machines?  That would make debugging this kind of thing a lot easier.

**Comment by pralitp** [comment]
Ha, I was asking myself the same question and is why I haven't yet looked into it yet.  I don't know of any.

We do have a machine downstairs that I used to use but you have to have your little chip thing to log in.

**Comment by rplzzz** [comment]
I've been experimenting with a couple of solutions to this problem and settled on two candidates:

1. If R offers a binding to `popen2`, I can't find it, so we can't get the output from CSVtoXML while using `pipe`; however, we _can_ get the status code for the command.  Since exiting with an exception sets a nonzero status code, this should allow us to detect (though not necessarily diagnose) failures.  That might be enough for our purposes.  On the other hand, if `pipe` isn't working on Windows, that doesn't help us here.  However, there's no reason why pipes shouldn't work on Windows, so maybe we can get this to work if we can grab a system to test on.

2. I reimplemented the call using `system2`.  I used a temp file so supply the stdin, since constructing a potentially huge string and holding on to the whole thing seems risky, memory-wise. The performance penalty seems to be about 13% relative to the other version, which isn't great, but we can probably live with it.  I tried it both with full output capture and with just capturing the status code, and there didn't seem to be much speed difference.  The status-code version is a little cleaner, but if we really want the error messages it's nice to know we can get them.  Of course, we don't know this version works on Windows.  It should, but then again, so should the pipe version.

So, the first question is, do we really need the error messages from CSVtoXML?  If we just want to detect errors, we can probably get by with just the status code.  

The second question is, what's going on on Windows?  We're not going to answer this today, but if we can figure out how to make the pipe version work on Windows, it is quite a bit faster.  Otherwise, we've got a plan B.

**Comment by bpbond** [comment]
Thanks for investigating @rplzzz . Yes, wtf wrt Windows? The R documentation clearly implies that _pipe_ works on that platform too.

It's good to know that there's a `system2` fallback that's OK–my guess is we can live with a 13% speed penalty.
