### ISSUE TITLE
driver() does not create xml's and gives warning

### ISSUE THREAD

**Issue by zarrarkhan** [JGCRI/gcamdata#1049]
After running driver(), script completes without errors, however no xml files are created. For each xml file that should have been create a warning message is produced. One example warning message is copied below:

> 6: running command '"java" -cp C:/Program Files/R/R-3.4.3/library/gcamdata/extdata/ModelInterface/CSVToXML.jar -Xmx1g ModelInterface.ModelGUI2.csvconv.CSVToXMLMain C:\Users\khan404\AppData\Local\Temp\RtmpSgqqQ4\file2780195f6eb6 C:/Program Files/R/R-3.4.3/library/gcamdata/extdata/mi_headers/ModelInterface_headers.txt xml//hector.xml' had status 1

**Comment by pralitp** [comment]
This has to do with the running the XML conversion which needs to launch Java to call the `CSVToXML` tool.

It turns out that `system2` does not automatically "escape" arguments (i.e. spaces in the path to the various paths) that need to get passed as arguments to the `CSVToXML` tool.  Doing this manually fixes it:

```
args <- c(
        "-cp", shQuote(java_cp),
        "-Xmx1g", # TODO: memory limits?
        "ModelInterface.ModelGUI2.csvconv.CSVToXMLMain",
        tmpfn, # Read from the temporary file
        shQuote(dot$mi_header),
        shQuote(dot$xml_file)
      )
```
