### ISSUE TITLE
Appveyor not able to install gcamdata.compdata

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#1052]
For some reason the Appveyor CI errors when trying to install `gcamdata.compdata`, reporting a bizarre out-of-memory error ("cannot allocate vector of size 1.9 Mb"); see my comment in #1044 . I worked around this in 101f947 by making suggested packages optional. This didn't get at the root problem, though...but I'm not sure what that is.

**Comment by pralitp** [comment]
I think the root of the problem here was running out of memory during the OLD/NEW tests.  We papered around this in #1079 by just skipping the whole thing as we don't generate the test data set anyways.  I think we can close this issue for now.  If we did actually want to run the OLD/NEW on appveryor I think we would have to find other ways to stay within the Appveyor memory limits anyways beyond this which should be it's own issue.
