### ISSUE TITLE
Using semi_join versus filter

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#1068]
It looks like `semi_join(x, y, by = "z")` is 25-30% faster than using `filter(x, z %in% y$z`.

If this is right, see how often the latter is used in code and change.

See also #1065

**Comment by russellhz** [comment]
This turns out to be true, except for when there are multiple filters applied at once, in which case it is often faster to have one call to `filter()` rather than use `filter() %>% semi_join()`. 

There were somewhere around a hundred places where it was faster to replace with `semi_join()` or `anti_join()`. I have changed these in #1210 . I also added this to the speed tips but am not planning to enforce it via tests because of the exception.
