### ISSUE TITLE
FAO data being read as integers

### ISSUE THREAD

**Issue by pkyle** [JGCRI/gcamdata#1085]
I just noticed, and this might apply to other places too, that all of the data files I looked at in the `inst/extdata/aglu/FAO/` folder have their data classified as integers. The reason these appear as integers is that the reporting units on most datasets in FAOSTAT are small enough that decimal values aren't needed, but the data should still be treated as numeric, not integer. I'll look into this in the next few days and submit a PR unless I hear otherwise.

**Comment by bpbond** [comment]
Just curious–why does this matter? Not a big deal, go ahead from my POV, just wondering from the department of "if it's not broke...".

**Comment by pkyle** [comment]
Oh maybe it doesn't! I had thought that the purpose of the exercise of manually specifying column types was to keep readr from "guessing" the wrong thing, and that specifically, we were trying to avoid mistaking integers with numeric/double columns. Altho, in re-reading [#1072](https://github.com/JGCRI/gcamdata/issues/1072), it looks like maybe the issue is when an integer is read as numeric, but not vice versa?

**Comment by bpbond** [comment]
There are at least two issues, originating from `readr`'s original poor decision (IMO) and then their recent change of behavior. The upshot is that now `read_csv` will _never_ guess something as integer. In this case, though, it's not a problem, since the original and pre-readr-1.3 data systems were reading these data as integer anyway. 

Anyway: it's not a problem as it currently stands, although we could add a note to the file header(s) with the explanation you gave above, I guess.
