### ISSUE TITLE
Feature request: build only dependent XML files

### ISSUE THREAD

**Issue by rjplevin** [JGCRI/gcamdata#1149]
I'm scripting some modifications to GCAM data and would like to generate only the XML files dependent on a given subset of the input CSV / R files. Is this possible?

**Comment by pkyle** [comment]
As far as I know, you can either generate all XML files, or just one at a time using the `stop_after = ` argument. For example, if you've made some changes that only apply to buildings and you just want to re-build the buildings sector XML file `building_det.xml`, you'd re-load and then run:
`driver(stop_after = "module_energy_batch_building_det_xml")`
After doing that, there will be just that one XML file in your `./xml/` folder
Unfortunately we don't currently have the capability to automatically run only the portions of gcamdata affected by changes made since the last complete run.

**Comment by rjplevin** [comment]
So does "stop_after" really mean to run only the indicated target? Or does it mean do everything up  to and including that target, as "stop  after" would suggest?

I see that there are facilities for plotting dependencies, so there should be (or could easily be) a way to query these dependencies. (That's why this issue is labeled "Feature request"!)

**Comment by pkyle** [comment]
"stop_after" will run the target function preceded by all required (i.e. upstream) dependencies. Only dependencies actually required by the target function are run, so it can be very fast. For example, running `driver(stop_after = "module_energy_batch_ccs_supply_high_xml")` takes 1.5 seconds, whereas `driver(stop_after = "module_water_batch_electricity_water_xml")` takes 90 seconds.
