### ISSUE TITLE
Question on running gcamdata supplied with older versions of GCAM

### ISSUE THREAD

**Issue by amnmalik** [JGCRI/gcamdata#1222]
Dear GCAM team,

I am currently working with GCAM 5.2 and looking for a way to "build" the gcamdata package supplied with that version. I am aware that the newer gcamdata versions use renv. However, how and from where can I look up the version dependencies for "older" versions of gcamdata for example the one bundled with GCAM 5.2?

Thanks in advance!

**Comment by russellhz** [comment]
Unfortunately we added in renv precisely because it was hard to know the "correct" dependency versions for older versions of gcamdata. The best place to look would probably be in the gcamdata description for GCAM 5.2: https://github.com/JGCRI/gcam-core/blob/gcam-v5.2/input/gcamdata/DESCRIPTION

However, I can't guarantee that you will avoid any issues based on those package versions. If you run into errors, the most likely culprits are `tidyr` and `readr`

**Comment by amnmalik** [comment]
Thanks!
