### ISSUE TITLE
Test code should make sure OLD_DATA_SYSTEM_BEHAVIOR blocks run

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#180]

**Comment by bpbond** [comment]
This may not be possible unfortunately, if the new behavior blocks produce significantly different output.

**Comment by rplzzz** [comment]
I'm not sure what you had in mind for this issue, but it seems like it should be possible to run the driver with `OLD_DATA_SYSTEM_BEHAVIOR`[1] on and off, asserting no errors on either one.  You could run the non-compatible version with output turned off so that only the compatible version would get written for the old-new comparison tests.

[1] I probably would have called it BACK_COMPAT.  Might have removed all the vowels too.

**Comment by bpbond** [comment]
That's basically what I was thinking, yeah.

The most efficient was would be to identify all the chunks that mention `OLD_DATA_SYSTEM_BEHAVIOR` and _just_ call them with the flag flipped, ensuring no errors.

**Comment by bpbond** [comment]
We're far enough along this isn't worth it, I don't think. We will need to have a protocol (tests) for when those blocks get turned on, but that can wait for now.
