### ISSUE TITLE
USA Alfalfa production in LA101.ag_FAO_R_C_Y

### ISSUE THREAD

**Issue by kvcalvin** [JGCRI/gcamdata#206]
We divided USA alfalfa production by 4 in LA101.ag_FAO_R_C_Y "for consistency with USDA". This needs more documentation. Why only this crop/region combination? Was there a problem with the FAO data?

**Comment by pkyle** [comment]
The basic problem is that the FAO fodder data are not maintained or documented, and only show up in one query ("Crops Primary") in the classic FAOSTAT data, so they might not be available any more at all. In comparing USA data with the USDA, it appears that several of the categories and numbers are made up by FAO (e.g., the same number reported in all years), but the major fodder crop in the USA is Alfalfa. FAOSTAT's reported Alfalfa production (~300 Mt/yr) is equal in all years to the USDA's estimate multiplied by 4, presumably because FAOSTAT is aiming to report harvest weight, whereas USDA (explicitly) reports dry weights. Between the two, the dry weight is what we would prefer, because that's what our animal production technology input-output coefficients assume for fodder crops. In any case, the reason for dividing by 4 here is for (a) consistency with the USDA, and (b) to get the correct number for purposes of tracking the inputs to the animal production technologies. The reason for not doing it elsewhere is that we don't have any evidence that it's the correct thing to do, because there's no documentation of the data or sources, my email to FAOSTAT's statistical office wasn't answered, and the people at FAO that I've asked in person have replied with some variant of "what fodder data?"
