### ISSUE TITLE
Ethiopia FAO data

### ISSUE THREAD

**Issue by kvcalvin** [JGCRI/gcamdata#207]
Ethiopia appears twice in the FAO data used in LA101.ag_FAO_R_C_Y. Both "countries" have the same iso code, but different country names. The old data system (and now the DSR) aggregate the two countries together, but more documentation/checking on the problem would be good.

**Comment by pkyle** [comment]
Adding the two looks to be correct, even though I don't know what Ethiopia PDR refers to; it seems to have transitioned from 1991 to 1995, and in those years, the total is smooth if the two countries are added together. Here are plots of wheat and sorghum, as representative (and relatively important) crops.
![eth_wheat](https://cloud.githubusercontent.com/assets/20807787/24667686/4b833fa4-1932-11e7-9aa8-b1e2b7187886.png)
![eth_sorghum](https://cloud.githubusercontent.com/assets/20807787/24667701/51e4842a-1932-11e7-9ac7-a94a40ec0cb8.png)

**Comment by rplzzz** [comment]
Apparently, the "People's Democratic Republic of Ethiopia" was the official name of the country from 1987 to 1991.  Why the data has the two overlapping is a bit of a mystery, but it turns out that the new government didn't actually take over from the transitional government until 1995, which is when the "PDR" is completely phased out of the data.  Therefore, I'd speculate that reporting was a little inconsistent during the transitional period.  Whatever the case, I think we can just file this under "because of reasons" and move on.
