### ISSUE TITLE
Methods of price aggregation and dollar year conversion in LB132.ag_an_For_Prices_USA_C_2005.R

### ISSUE THREAD

**Issue by rynacui** [JGCRI/gcamdata#221]
In the old DS, producer prices of agricultural commodities were calibrated to the 2001-05 average, with the following steps:
1. Calculate the 5-yr avg price and avg production by item and country.
2. Aggregate price to GCAM commodity and region, weighted by production.
3. Convert to 1975$ using the deflator `conv_2004_1975_USD`.

We may consider change the order of these steps to:
1. Convert all nominal prices to 1975$ using year-specific deflators (and country-specific USD deflators in a few cases where US price is unavailable and other countries' are used).
2. Aggregate all 1975$ prices in each year to GCAM commodity and region, weighted by production in each year.
3. Take the 5-yr avg weighted prices.

We may also want to make it consistent in other similar occasions that involve prices. Here all the input price data are in USD. If other local currency is involved, there is also a currency conversion step in the beginning, using market exchange rates to nominal USD, and then country-specific USD deflators to constant USD. [UNSD](https://unstats.un.org/unsd/snaama/dnlList.asp) has the country-specific deflators to 2005$.

**Comment by pkyle** [comment]
All sounds good! Just on a practical note, from the perspective of the model, what is most important is the difference between producer prices and production costs. No doubt there's benefit to calculating prices here in similar ways to how prices are calculated elsewhere, or otherwise improving the methods, but for the model function/performance, we need consistency between prices and costs. Note also that the input parameter "calPrice" doesn't take a year--so, as currently structured, there's no place in the model for calibration prices in multiple base years. Though also no reason why that couldn't or shouldn't be calculated.

**Comment by rynacui** [comment]
@rplzzz @swaldhoff Here is the issue I opened up a while ago, about the Ag price aggregation and dollar conversion method. I did not include it into the `old_data_system_behavior` while I was working on this chunk. How would you like me to address this?

**Comment by swaldhoff** [comment]
I think it would be helpful if you could add the corrections to the price and cost data processing with the old_data_system_behavior function.
