### ISSUE TITLE
L101.Population.R comment re population datasets used

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#232]
Lines 40-41 in `L101.Population.R` say

```
#Future population in the GCAM-SSP (paP) scenarios
#for now use SSP population for both SSP and gSSP; revisit this after consulting GCAM-China team
```

Does this need to be followed up on?

**Comment by pkyle** [comment]
@d3y419 Did you write that comment, or was it Jeff? Either way I wasn't involved here...the fundamental issue brought up by the comment is that SSP2 socioeconomic assumptions are crazytown in both China and Nigeria, and we may want to patch it up before the community agrees to a revision, because that might just take a decade!

**Comment by pkyle** [comment]
But also this isn't a revision for this present round of work--should be its own research effort, core model proposal, etc.

**Comment by rplzzz** [comment]
I've added this as a task in our GCAM backlog, so I think we can close it out here.
