### ISSUE TITLE
Multiple datasets into same XML

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#26]
Pralit notes that there are cases in the d.s. where multiple datasets flow into a single XML, and the ordering is important. We'll need to look at this.

**Comment by pkyle** [comment]
Yeah, good point. I think the only case in aglu/energy modules is the bio_hi.xml file in AgLU, which changes yields and carbon contents of bioenergy crops, and those parameters are set in different R code files. But that file is not long for this world (isn't in the integration branch). There is at least one case of this in the emissions module (all_fgas_emissions.xml, created by L241 and L252), but my guess is this and any others could be modularized without much problem.
The issue I've had wrt this issue is that we can get XML files that are identical in the model (every parameter equal) but that will nevertheless appear quite different (comparing the text), if R code files aren't run in the same order.

**Comment by pralitp** [comment]
This should be taken care of it the approach that I took on the branch I just created (I'll open a pull request in the next day or two and reference this issue).

Basically the current level 2 just publish the tables that the current data system would add to a "batch xml file" as output.  And a separate chunk will input them back in and do the XML conversion.  So each "batch xml file" now get's it's own chunk.
