### ISSUE TITLE
Documenting input data

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#28]
There are a number of ways to document input datasets _not_ generated by the data system itself, and how we do it will sometimes depend on the data.

* Separate file - e.g. `xxx.csv` accompanied by `xxx-metadata.txt`
* Header in data file
* In-code (if specialized for reading in one particular dataset)

**Comment by bpbond** [comment]
Could have generic file reader send any comment lines (`#`) at top into `add_comments`, and could even look for title/units too

**Comment by ssmithClimate** [comment]
@bpbond  - you also had mentioned at one point yaml as an option as well? (Don't think I got that right).

A few thoughts.

We , collectively, have a lot of work to do to document the sources of GCAM data. So this will need to be incremental - we'll need to slowly build this up over time. (For example, at some point the expectation would be during code review that inputs have metadata documenting their source. So we would natural build up metadata as the model is revised.). Sort of obvious, but just to say that.

In the CEDS system we accumulate meta-data, so that meta-data describing each data source accumulates as it is used to that data produced subsequently accumulate the meta-data from all files that are used. That may or may not be something we want to do for GCAM. 

Should there be any kind of structure? Given the diversity of GCAM input data it would need to be flexible. One option could be to be entirely free form (e.g. just whatever text the user puts in) - I suspect we may want this no matter what, or we could have options for specific fields as well (country/region, journal paper/report reference, data type, ???).

**Comment by bpbond** [comment]
Initial thoughts - I'd suggest a two-pronged approach for now:

1. 'Generic' (most) CSV files should be documented via a header at the top of the file, with header lines prefixed by `#`. As we bring files from the old data system into the new one, we check and make sure documentation looks good and update/add as necessary. Issues are opened for problems/unclear datasets. As the data system reads these files in, it assigns the first line to the object's `title` attribute, and other lines to `comments`. It could scan for a "Units" line too and fill that in. For example:

```
# Title of the table below 
# Units: ha
# Description of the table
# Optional more description lines...
col1, col2, col3
1, 2, 3
4, 5, 6
```

2. Some files will have specialized routines to read them--e.g. see my PR #71 . In this case, the relevant metadata can be filled in by the code itself.

@pkyle ? @pralitp ?

**Comment by ssmithClimate** [comment]
A number of csv's now start with:
# File:iso_to_GCAM_region.csv,,,
# Description: Maps iso codes to GCAM regions (including composites as necessary),,,
so perhaps we want to accommodate that.
(I like the "File: " tag, which is also a nice check that the # lines weren't simply copied from somewhere else.)

**Comment by bpbond** [comment]
Any standard is fine, as long as there is one.

**Comment by pkyle** [comment]
Agreed that any standard is fine, and the suggested one looks good to me. I know some of the csv's have the wrong metadata, just because there were a lot of them and I didn't pay a whole lot of attention to that because the top-line comments weren't being used by the data system anyway.

**Comment by bpbond** [comment]
So in the DSR trainings we are (briefly) discussing the importance of putting eyes on all input files, and fixing/flagging for followup ones with insufficient documentation. Would we would like to specify that, when possible, they put on a standard header as well? E.g.

```
# File: (name of file)
# Title: (title)
# Units: (units)
# Comment: (comment lines)
header...
```

**Comment by ssmithClimate** [comment]
I would support this (as Ben said, where possible). Might we want to call the tag Description instead of Comment to be more specific? I'd like suggest we have the (optional) tag Reference:, since in some cases there will be a specific reference source for the data. 

Would multiple line comments/description all require a tag, or just inherit the last tag used?

If one pasted a standard reference (that had special characters and URLs), would that cause a problem on read-in? (I seem to recall there were some characters that sometimes caused problems, but can't remember what they were).
 
# File: (name of file)
# Title: (title)
# Units: (units)
# Description: (comment lines)
# Reference: (paper or report reference, if applicable, otherwise omit.)

**Comment by pkyle** [comment]
That's a good point--for data from other sources, often an external URL is provided, and we should check/update them, and certainly keep them. Also a lot of the datasets have multiple units. Some have different units in different rows, with a column indicating the unit (e.g., see socioeconomics-data/level0/IMF_GDP_growth.csv). Others have different units in different columns, where the column header has info about the unit (e.g., energy-data/level0/H2A_Prod_Tech.csv). So we'll either need to be flexible on what is required of the "Units" attribute (e.g., "see table" is OK), or break up / re-structure the tables that violate the units rules.
One more consideration is that as implemented in the current data system, comments can not have commas, so none of the current comments do (whether manually written in the exogenous CSVs, or added as comments to CSVs built from the code). Not sure if that's something that will change with the DSR.

**Comment by bpbond** [comment]
Good point, Page. Re units - my sense is that we don't want to grapple, right now, with the problem of multiple-unit tables. We're not going to enforce unit checking, so we'll just tell people to enter "(various)" or something like that in those cases.

Commas - that's an Excel quirk. If you don't use Excel to edit the CSVs, this problem goes away. Good to remind folks of this though.

OK, seems like the consensus is we'll ask people to use the following header format:
```
# File: (name of file) - NB not really necessary, though I don't care hugely
# Title: (title, 1 line)
# Units: (units, 1 line)
# Description: (1 or more comment lines) - "# Comment:" is a synonym
# Reference: (1 line)
```

All lines are optional for now, though strongly encouraged. Files without good documentation need to be brought up to spec, or at least noted as an issue.

OK?

**Comment by ssmithClimate** [comment]
Suggest reference could also have multiple lines (could be more than one reference, seems cleaner to have one reference per line. That facilitates possible parsing into a reference list, etc.).

So what would be best for processing multiple lines?

A)
# Description: Line one
# line 2
# line 3...

or 

B)
# Description: Line one
# Description: line 2
# Description: line 3...

Ben, you seem to be pointing to option A. Option B has less ambiguity, but perhaps its easier to import longer blocks of description text if only one line requires a label? Thoughts?

**Comment by bpbond** [comment]
The thing about multiline comments (i.e. option A above) is how do we know when they end? As a first pass, I'm going to assume the simplest thing--that they end when the comments end.

**Comment by ssmithClimate** [comment]
When comments end or the parser runs into a new tag.

**Comment by bpbond** [comment]
Trickier but yeah, I think that's right. OK. Closing this issue. Further comments, if necessary, in #78 .
