### ISSUE TITLE
Units!!!

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#29]
The benefits of forcing units specification are MANY. Think about this.

Internally one could have e.g.

```R
x %>%
  add_units("variable_name", "units") %>%
...
```

Then later chunks have to assert they know units, Hector-style:

```R
x <- get_data(all_data, "x", units = UNITS_NAME)
```

**Comment by bpbond** [comment]
Chunks now have to provide units with all their outputs (see 3a11df8) but not enforcing the know-units-to-get-data possibility above.

**Comment by bpbond** [comment]
@rplzzz @pkyle @kvcalvin @pralitp does this seem reasonable? For our first pass at DSR, require units to be attached to output data, but NOT require assertion of units to access data?

**Comment by pralitp** [comment]
That sounds reasonable to me.

**Comment by pkyle** [comment]
From my understanding, this is only enforced for the data objects being written out to CSV, and not the ones that are just stored (or not) mid-stream. That sounds fine--the mid-stream ones are the ones that tend to have different units in different columns. Still, there might be some files with multiple units; the only ones I can think of are the cement-related files (energy/L*321.*) with input-related information, because the production technology takes inputs of energy (heat, electricity) and materials (limestone). So, the units are different depending on the row. That could be indicated in a table's meta-info (e.g., right now I just write the units as "GJ/kg and kg/kg" in a table of IO coefficients), or we could just require each data table to have a column for the units, and that way the units can differ by row.

**Comment by bpbond** [comment]
OK, thanks, seems like this is good for now, and gives us a foundation to build on later.
