### ISSUE TITLE
GCAM_sector_tech.csv has transportation incorrectly labelled.

### ISSUE THREAD

**Issue by d3y419** [JGCRI/gcamdata#303]
this commonly used mapping file has transportation fuel labelled "technology" and car size labelled "fuel".

the problem occurs when coders take this at face value at try to left_join "sector" and "fuel". you end up missing out of the true transportation fuel. 

as far as i can tell this is only transport. elec and resid are fine.

tag here if your chunk has the same issue. there's good chance you do, if you have transport chunk.

![image](https://cloud.githubusercontent.com/assets/23386151/25514274/bee940c2-2ba9-11e7-8afa-f3698a89fef2.png)

two potential solutions requiring consensus:
1. label correctly in the mapping file. but then it's no longer consistent with GCAM structure.
2. change the label to simply "sector" subsector" "technology". not immediately intuitive, but this keeps the GCAM structure. 

please cast your votes!

**Comment by d3y419** [comment]
@pkyle @bpbond

**Comment by pkyle** [comment]
Note that this is only used in the emissions module; while it's called GCAM_sector_tech, it isn't actually used in building and mapping GCAM sectors and technologies. I think it's only used for assigning emissions from inventories to technologies in the model. Given that, the impacts of this inconsistency in naming is probably confined to only one or two code chunks. Not sure if that helps!
As for "vote", I'd say do what works; I can't tell whether either of the options that you gave above would cause a train wreck, or maybe both of them! Note that the table already has supplysector/subsector/technology columns, and those are labeled correctly so you don't really want to be changing them.

**Comment by bpbond** [comment]
See also #258

**Comment by bpbond** [comment]
Adding milestone "Version 2" to this. If it should be closed instead, please do so.

**Comment by russellhz** [comment]
@d3y419 @pkyle I am trying to close old issues and wanted to check on this. I took a look and it doesn't seem easy to change the "fuel" label for transport without some slightly annoying code changes (basically just splitting up how the file is joined into two separate pipelines). If we want to fix this, GCAM_sector_tech.csv file should be split into multiple files. Given that everything is working, my instinct is to say it's good enough and close the issue, but I'm willing to make the changes if others think it is worthwhile.

**Comment by pkyle** [comment]
Yeah I'm sorry, as noted in my comment above I don't know what to recommend as the best way to deal with this. It would take some looking into, not the kind of thing where I can just make an armchair recommendation. Feel free to either close the issue and make a Jira issue / task out of this, or just leave it open.

**Comment by russellhz** [comment]
I took a stab at removing the `fuel `column (which is redundant with the subsector column for everything except transport) and adding a `UCD_match `column. Ultimately, I think this just adds more confusion, as it requires a changes to multiple modules to join in the same file in different ways for different sectors. If we split the file into multiple files by sector type, a similar problem would arise, although this might be a better strategy.

I also noted this comment on line 75 of `module_emissions_L114.bcoc_en_R_S_T_Y`:
` # Join in the sectors and fuels that correspond to the default BC and OC emissions coefs # Note: many of the sector/tech combinations in the GCAM_sector_tech mapping file are duplicates, so # the appropriate function to use whenever this table is joined in is the 'first' match. Dealing with this # would require a third "by" column (fuel), which would require modifications to the GCAM_sector_tech  # mapping table.`

Since this is working and there is no obvious great fix, I am going to close this issue here. I will open a JIRA issue to note that we could think about redeveloping the mapping file.

**Comment by ssmithClimate** [comment]
Is there at least something that could be added to the comment field to note that the labels shouldn't be taken literally?

**Comment by russellhz** [comment]
@ssmithClimate sure, I just added this to #1184
