### ISSUE TITLE
EDGAR_nation ISO codes

### ISSUE THREAD

**Issue by cahartin** [JGCRI/gcamdata#331]
The file EDGAR_nation appears to be a conversion between upper and lower case ISO codes.  However, there are 9 countries within the file that are not a simple capitalization.  Should we have a file of exceptions? It seems like we don't necessarily need the entire EDGAR_nation file. 

Exceptions:
UMI
SGS
ROU
IOT
ATF
HMD
ATA
SEA
AIR

**Comment by bpbond** [comment]
What happens with these exceptions? There's actually a code change? Do we know why?

**Comment by kvcalvin** [comment]
Yes. Let’s chat when you get in.

**Comment by rplzzz** [comment]
FYI, there is actually a utility function to downcase the ISO codes and change the name of the ISO column to 'iso' if necessary.

As for the exception codes, I see our old friend Ro(u)mania is in there, and the rest seem to be bogus codes (non-independent territories, Antarctica, and a couple that codes don't even appear in the table I'm looking at).

**Comment by cahartin** [comment]
@rpl originally i was using `toupper` or `tolower` to convert, but that's when i realized there were a few countries who weren't a straight conversion.

**Comment by kvcalvin** [comment]
@rplzzz: isn't `ROU` the correct code for Romania? That is what wikipedia says. If so, it seems like we are going through some hoops to make it wrong.

**Comment by rplzzz** [comment]
The code for Romania changed from ROM to ROU in 2002 (see: https://web.archive.org/web/20110722001502/http://www.iso.org/iso/newsletter_v-3_romania.pdf).  As a result, both variants appear in our sources.  It doesn't matter which version we use (i.e., the "hoops" are the same either way), so long as we pick one and stick with it.  

I'm not sure why we decided to go with the old code instead of the new one.  Someone made that decision early on, and we've kept it in the interest of backward compatibility ever since.  Whenever the code base stabilizes after the current round of upgrades we could change it to use the newer code, if people think it makes sense to do so.

**Comment by kvcalvin** [comment]
More information on this issue: 
The LDS data uses 'rom'. EDGAR and GDP use 'rou'. The GCAM iso to region mapping uses 'rom', so all of the country to iso maps use 'rom'. For consistency, we either need to (1) switch the LDS and mapping files to use 'rou' (which is the current iso), or (2) switch EDGAR and GDP to use 'rom'. For now, I suggest we use 'rom' since it involves the least amount of work. I also think we should use Robert's "change_iso_code" function, rather than opaque mapping files (e.g., EDGAR_nation). I'm opening a PR now to fix the one data file that uses EDGAR nation now.

**Comment by bpbond** [comment]
Should this be closed?

**Comment by kvcalvin** [comment]
@bpbond: I think it depends on whether we like this as a long-term fix.

**Comment by bpbond** [comment]
Since this EDGAR-specific, I'm going to close it, with a reference to this discussion over in #105, which is about ISO regularization in general.
