### ISSUE TITLE
Code not flexible for updating emission information

### ISSUE THREAD

**Issue by cahartin** [JGCRI/gcamdata#352]
In the future if we wanted to use updated emissions data out to let's say 2016, we can't easily add them in.  Within the code (L131.nonco2_proc_R_S_T_Y) it is hard coded to filter out any information past 2008.  

For example, EDGAR VOCs have 2 more years of information than the other gases.  Now we are filtering out this information. 

`EDGAR_gases %>%
      # filter out years 2009 and 2010 for NMVOCs only
      filter(Non.CO2 == "NMVOC", !year %in% c(2009, 2010))`

**Comment by bpbond** [comment]
Could you clarify? Is this a bug? I need a better description of the problem please.

**Comment by rplzzz** [comment]
@cahartin Probably what you want to do is define a constant with a name something like "EDGAR_LAST_EMISSIONS_YEAR".  Then filter for `year <= EDGAR_LAST_EMISSIONS_YEAR`.  Then we can easily change its value. 

You should make that change sooner rather than later, as the existing filter is very brittle (it takes out 2009 and 2010, but what happens if a revision to the database has even later years in it).

**Comment by russellhz** [comment]
Issue can be closed since, as of CMP320 [Emissions Base-Year Update], GCAM is now calibrated to CEDS.
