### ISSUE TITLE
AGLU input file: USDA_cost_data

### ISSUE THREAD

**Issue by abigailsnyder** [JGCRI/gcamdata#365]
This is housed in extdata/aglu in the new DS and in aglu-data/level0 in the old DS. 

This input file does not match itself in the old versus new DS. For example, in the old DS, 
Corn, Primary output is 366.459 in 1996.
In the new DS, the value is 363.9184. This mismatch persists throughout the table.
So using the file `USDA_cost_data` that is already in the new DS repository should fundamentally lead to a mismatch in outputs. I'm guessing anyway, it's not like I've finished the translation and put it through the tests yet. 
Has this file been updated? Is the mismatch intentional?

I can easily bring the file over from the old DS if that's not an issue, but I wanted to check first.

**Comment by bpbond** [comment]
I just ran `git blame` on this file and got...myself. Hmm. I have no idea why it would differ from old to new. Uh...any ideas @pkyle ?

**Comment by pkyle** [comment]
OK this one might be on me...not sure. In switching from the AEZ-based to the basin-based model (i.e., from master to integration/water-ssp), the "USDA_cost_data.csv" table itself changed, as we went from using sub-national cost data to national averages. The table in the gcam-data-system-OLD/aglu-data/level0/ folder is correct. The table in inst/extdata/aglu is incorrect, and you can tell because there's a column for "Region" (e.g., Eastern Upland in the first few rows). So, we should update the usda_cost_data.csv in the new data system.

**Comment by pkyle** [comment]
Might want to check who added the inst/extdata/aglu/usda_cost_data.csv file, but either way it's probably irrelevant b/c I think this is the only R code chunk that uses that data table, so switching it shouldn't cause a trainwreck elsewhere

**Comment by abigailsnyder** [comment]
great, I will copy it over. Thanks!

**Comment by pkyle** [comment]
Cool...but I just noticed that I didn't update the description: "Itemized costs by crop and sub-region of USA". It's not by sub-region. Should read something like "Itemized costs and returns of crop production by crop; USA national averages"

**Comment by abigailsnyder** [comment]
Thanks for that information, that's an easy update for me to make.
