### ISSUE TITLE
LA124 - choice of norm_year and algorithm

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#460]
```R
    norm_year <- max(HISTORICAL_YEARS) # originally was hardcoded as 2010
```

@rplzzz asks in #456 , re line 145 in `LA124.heat.R`:

>Are we sure we want norm_year to depend on the choice of historical years? It sounds like we're picking a base year to use for calculating fuel shares (but the comments above are a little confusing, so it's hard to tell). Since we use this to replace zero outputs in other times, it's not clear to me that we want it to change just because we are changing our definition of "historical years".

>Having said that, if the purpose here is to fill in small nonzero values for years recorded as zero, then maybe we should pick a constant small value instead of whatever the heck we're doing here. My concern is that if we change the historical years we'll wind up with slightly different values in the new scenario. The result would be that values in early years (say, 1990) would be different depending on whether we are ending the historical years in, say, 2005 or 2010.

>I guess my question is, why is it necessary to replace 0 district heat output values with 10-3 times their value in some possibly arbitrary year, rather than with a fixed small value? Also, what happens if the district heat output happens to be zero in norm_year? Then this fix doesn't fix anything.

>Worse, if the output is nonzero in 2010 and zero in the new max historical year, we'll get an unexpected failure when we go to run GCAM over the new configuration. That is likely to happen many months after we have forgotten about what we did in this chunk, and it will be devilishly hard to track down.

@pkyle @jhoring any comment?

**Comment by pkyle** [comment]
The reason for doing this approach instead of just setting each value to 1e-3 (or some other small number) is that this way, we'll get generally correct technology shares and therefore share-weights. 2010 is used as the year because it's probably the most reliable, and district heating systems tend to be old, so the fuel shares probably haven't changed that much since the 1980's (the years where this problem occurred).
If we just set each fuel to the same small number, then the technology options will all get equal share, and if that occurs in a year that is used as the final calibration year, then the district heat prices (and subsector share-weights) won't be computed correctly, which could distort the secondary output revenue from the heat produced by MAINCHP power plants. That said, this is a minor distinction.

**Comment by rplzzz** [comment]
I don't understand how this ensures correct technology shares.  Is the idea here that if one of the technology values is zero, then they all are?  Otherwise you get one output at 10<sup>-3</sup> times its 2010 value, while everything else is at whatever is in the data, and that ratio is not going to bear any kind of relationship to the technology shares in 2010.

It's also not clear how it will affect the share weights, since they will be determined in 2010, since it's the final base year.  This is specifically filling in years prior to that.  Formally we calculate share weights in the earlier base years, but they aren't used for anything.

Anyhow, none of this gets at the _real_ question I was asking, which is, should this really be calculated from `max(HISTORICAL_YEARS)`, or should it be locked to 2010?

**Comment by pkyle** [comment]
Sorry I misunderstood the question. Could be hard-wired to 2010 or the max historical year, it doesn't matter.
I think reading the old comment in the code might help for why we're doing this--it's not where one tech is zero, it's relevant where all techs are zero. Where all of the heat produced in a given region/year is a by-product of electric power plants set up in a cogen configuration. The model doesn't have any purpose-produced district heat, and therefore nowhere to dump the secondary output heat, and nowhere to get a price. If we don't do anything, we get model solution failure, and if we are using one of these years (generally in the 1980's from my memory) as the final calibration year (i.e., running in hindcast mode), then the share-weight problems become more significant.
What this is trying to do is to figure out, for the minuscule amount of purpose-produced heat that we're going to assign just for purposes of having the market, what should be the sharing between coal, gas, oil, and biomass? If our default on all techs is 1e-3, then all techs will get 25%, and that's not what we want.
