### ISSUE TITLE
manufacturing_water_mapping is fragile

### ISSUE THREAD

**Issue by pralitp** [JGCRI/gcamdata#542]
The mapping file `manufacturing_water_mapping` maps a continental regional definition to the GCAM regions by the 32 GCAM region names.  This sort of thing is bound to happen but if anyone wanted to change the region definitions or even just the region names they will need to update this file too.  It may make sense to move this / keep in together with other regional mapping files.

**Comment by pkyle** [comment]
I also removed this in my water-ssp-efw branch; it isn't necessary, as we can just map Vassolo and Doll's macro-regions to countries rather than GCAM regions. Then countries are aggregated to GCAM regions post hoc.
Might it be a good idea to merge in some of the changes from the efw branch before releasing this?
