### ISSUE TITLE
Inputs to LB1322.Fert from H2A model

### ISSUE THREAD

**Issue by aarony2j** [JGCRI/gcamdata#554]
LB1322.Fert #529
Hi Page, I opened this issue to address Marshall's comment on the above Fert chunk. Can you say more about data taken from the H2A model for this chunk and whether anything should be updated or better described?
```
I coincidentally know that the H2A is the DOE EERE Hydrogen program's analysis model. The inputs in the level 0 file are based on a scenario using a version of that model for certain parameters potentially a long time ago. You can add a citation, even a web link to that program (https://www.hydrogen.energy.gov/h2a_analysis.html) but you would have to ask Page about any more specifics. Like, do we have the model saved with those inputs, or is it from a long time ago. What to do..., we can define H2A and provide a link. Ask Page if we know anything more about it.
```

**Comment by pkyle** [comment]
Marshall was the one who queried the data! I remember some specifics but they're best confined to the dustbins of history. In general, the data were queried so as to return reasonable and realistic estimates for the entire USA region, which was not straightforward because the H2A model was geographically resolved (e.g., metropolitan areas within the US). The NEcosts printed in that H2A_Prod_Tech.csv table were backed out of H2A's break-even price (i.e., final production price), minus the fuel IO coefficients times the fuel prices. The NEcosts are in 2005$ per kg of hydrogen, and the IO coef units are included in the variable names.

**Comment by aarony2j** [comment]
Thank you, Page. Marshall, as a reviewer, do you want to modify anything more on the H2A file? As it is, the header of the H2A file is:
```
# File: H2A_Prod_Tech.csv
# Title: H2A characteristics of hydrogen production technologies
# Units: Cost is 2005$/kgH; IO is btukg
# Source: H2A is the DOE EERE Hydrogen program's analysis model (https://www.hydrogen.energy.gov/h2a_analysis.html)
```
I can put some of what Page said in a comment line. Whatever you think is best.

**Comment by pkyle** [comment]
Uh, change that IO to btu per kg. No reason to leave the special characters out of a comment!

**Comment by aarony2j** [comment]
Nice catch! Especially since I used it just before for $/kgH

**Comment by aarony2j** [comment]
@mwisepnnl Hi Marshall. If possible, can you give the final say on this issue today? I need to create a new PR to include a "/" to the unit, and it would be nice to roll in any other final changes. Thanks!

**Comment by aarony2j** [comment]
Spoke with Marshall - fine as it is now.
