### ISSUE TITLE
What is the source for GAINS data (GAINS_activities.csv, GAINS_emissions.csv, gains_to_gcam_sector.csv)?

### ISSUE THREAD

**Issue by russellhz** [JGCRI/gcamdata#575]
My guess is it's something from Rogelj et al.

**Comment by ssmithClimate** [comment]
Best reference for this, since it gives the context as well, is:

Rao S, Z Klimont, SJ Smith, R van Dingenen, F Dentener, L Bouwman, K Riahi, M Amann, B Bodirsky, D Van Vuuren, L Reis, KV Calvin, L Drouet, O Fricko, S Fujimori, D Gernaat, P Havlik, M Harmsen, T Hasegawa, C Heyes, J Hilaire, G Luderer, T Masui, E Stehfest, J Strefler, S van der Sluis, and M Tavoni (2017) "Future Air Pollution in the Shared Socio-Economic Pathways." Global Environmental Change 42, 346–358. http://dx.doi.org/10.1016/j.gloenvcha.2016.05.009.

**Comment by russellhz** [comment]
thanks @ssmithClimate !
