### ISSUE TITLE
State-level floorspace data written by (an earlier version of) GCAM_USA, but used as an input to the energy system. Should it be revised?

### ISSUE THREAD

**Issue by aarony2j** [JGCRI/gcamdata#578]
Regarding,
A44.flsp_bm2_state_comm.csv and A44.flsp_bm2_state_res.csv
written by
LA144.Commercial.R and LA144.Residential.R in an earlier version of GCAM-USA.

See Aaron - LA144_building_det_flsp #549, where the discussion originated.

**Comment by pkyle** [comment]
I just wanted to provide some hopefully-helpful commentary on this, because it's a bit more complicated than "just fix it". Note that this is probably more of an issue for JIRA rather than Github, as this issue pertains to our fundamental data processing methods, not as much our implementation.
One thing to note up front is that for several of our clients (for specific studies/versions, not the core), we've been asked to revise our floorspace numbers for the USA so as to be consistent with the NEMS model (whose results are published each year in the Annual Energy Outlook, or AEO). That applies to studies using the USA region as well as ones using the 51 states (GCAM-USA). The EIA maintains several datasets that are typically used to estimate floorspace in the US, and for the residential sector the NEMS total is something like ~17 billion square meters, whereas the Residential Energy Consumption Survey (RECS) has more like ~20 or ~22, depending on whether non-space-conditioned floorspace is included. There are other estimates as well but those are the ones we've used in the past. For the commercial sector, the agreement between AEO and CBECS is better, but the issue nevertheless remains. In the functional forms of the model, the specific base-year quantity actually matters because our "satiation level" is hard-wired to some number of square meters per capita; future growth in floorspace and energy demand is therefore influenced to a large extent by the base-year level.
What I'd probably recommend (with some benefit of hindsight) is using the NEMS-based estimate, published in the AEO for each available year. In each AEO release, the base year lags the present by 3. So, for example, the 2010 floorspace number would be in the 2013 AEO. The historical versions are available back to 1996, with a base year of 1993. For the residential sector, AEO Table 4 includes the number of housing units and the average square footage, which can be multiplied to get an inventory of total floorspace. The commercial total is available in Table 5. Those are the numbers we ought to have in the model. I've already compiled the base year data in Tables 4 and 5 for each annual edition of the AEO from 1996 to 2013 in the following tables: EIA_AEO_Tab4 and EIA_AEO_Tab5. They should already be in the data system (old data system path was gcam-usa-data/level0).
Then, in GCAM-USA (i.e., the 51 states), we can use our methods that we currently use (i.e., RECS and CBECS), but scale the data so that the national totals are equal to the numbers derived above. That way we have agreement between GCAM-USA and the USA region of core GCAM, and we check the box for the clients that expect our data to match NEMS.
For the pre-1993 years, we'll need to expand on that method; with RECS and CBECS we do have estimates back to the 1970's, but we don't want a data-source-switching discrepancy in 1993, so probably best to just scale back the data from 1993 to the prior years using RECS- and CBECS-derived ratios. Sorry if that sounds complicated--I promise it isn't too bad, and happy to help if/when it comes time to implement!

**Comment by aarony2j** [comment]
Thanks @pkyle ! After doing enough of these chunks, I can picture the steps in my head ;)
What's next for this issue? Do we mark it to be done in the next round? The original PR has been merged.

**Comment by pkyle** [comment]
That's a good question! @bpbond are you keeping a list of issues to address over the next few months? I could make a Jira issue for it, but I'm just thinking it would be good to evaluate this one in the context of all of the others that people have noticed, so that we can prioritize.

**Comment by bpbond** [comment]
Yup, we're collecting them here in GitHub issues. I'll tag this appropriately and we can come back it later.

**Comment by russellhz** [comment]
Moved to JIRA (JGCRI-437 and JGCRI-441)
