### ISSUE TITLE
A31.globaltech_shrwt.csv year column wrong in old data system?

### ISSUE THREAD

**Issue by russellhz** [JGCRI/gcamdata#586]
2019?? Is that supposed to be 2015?

![screen shot 2017-07-31 at 9 45 04 am](https://user-images.githubusercontent.com/25437326/28780526-0a831966-75d5-11e7-93b5-4b3c30ce53e1.png)

**Comment by pkyle** [comment]
It looks unnecessary, and I didn't make this table, but often I did use tables with a 2019 year. For example, if we're bringing in Hydrogen as an energy source in 2020 but not before, then then the share-weight table should include a 2019 column with 0 share-weights, followed by a 2020 column with positive share-weights. That way, if someone sets the model timesteps to 1 year, and runs 2016-2019 as model time periods, we don't mistakenly get hydrogen in 2016 due to linear interpolation.

**Comment by russellhz** [comment]
Thanks @pkyle! I wouldn't have thought of that.
