### ISSUE TITLE
L241.en_newtech_nonco2 outputs 

### ISSUE THREAD

**Issue by kdorheim** [JGCRI/gcamdata#649]
Output returned by the old data system renames the csv files from `L241.nonghg_max_reduction` to `L241.nonco2_max_reduction`. The new ds returns csv with the names containing  the `nonghg`. How do we want to name the outputs from this chunk in the new ds? 

``` 
write_mi_data( L241.nonghg_max_reduction, "GDPCtrlMax", "EMISSIONS_LEVEL2_DATA", "L241.nonco2_max_reduction", "EMISSIONS_XML_BATCH", "batch_all_energy_emissions.xml" ) 
write_mi_data( L241.nonghg_steepness, "GDPCtrlSteep", "EMISSIONS_LEVEL2_DATA", "L241.nonco2_steepness", "EMISSIONS_XML_BATCH", "batch_all_energy_emissions.xml" ) 
```

@pkyle  I spoke with @bpbond and he said to check with you

**Comment by bpbond** [comment]
I thought this was probably a typo?

**Comment by pkyle** [comment]
I can confirm it was a typo, though I was not the author as this is the emissions module! Either one will work so the easier one (nonco2) is probably what I'd recomment. Here's a more complete description if it matters: non-GHG in this case is more descriptive, as the CSV file does not include CH4, N2O, or the F gases. So while "nonCO2" does work, "nonGHG" is more descriptive of this particular basket of emissions. However this level of descriptiveness isn't crucial, and it looks like nonco2 is the easier one because it's what the old file is called, so again it's what I'd recommend.

**Comment by bpbond** [comment]
Thanks, Page.
