### ISSUE TITLE
Consider creating the water mapping files by demand type

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#663]
In #651 @skim301 said:

>I would consider creating the water mapping files by demand types (irr, dom, ind, ...) rather than by variable type and break up the final water mapping xml file by demand types to reduce the file size and allow ease of modification. But this is for future work too.

**Comment by pralitp** [comment]
FYI, when this work was done the first time around that was the way it was done -- separate files for each water sector.  In the process of tidying things up it became clear it was beneficial to put them all together but at this point I don't remember exactly off of the top of my head why it was the case.  I can try to look back at logs but my instinct was it somehow made it a lot easier to generate constrained vs unconstrained scenarios.

**Comment by skim301** [comment]
Yes, Pralit. I think it is the case that it is easier to run constrained vs. unconstrained by just swapping a single mapping file, where the source of the water is either a generic unlimited resource or the actual constrained basin resource.

I think that if we begin to do more focused sectoral water studies on either ag or other end-use, where we're always running in constrained mode, then it may be useful to have it separated out.

**Comment by russellhz** [comment]
In the most recent gcam-core on stash, `zchunk_L203.water_mapping.R` has been replaced by `zchunk_L203.water_td.R`. The resulting xml file is about 40-50% the size of the old file. However, it does not separate the different demand types. I'm going to close this issue here, since it's more of a GCAM question and it's not clear what the best option is. If we want to keep the issue open, it probably is better suited for JIRA.
