### ISSUE TITLE
Use `gcamusa.STATES`

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#762]
@russellhz added a `gcamusa.STATES` definition to `constants.R`. We'd like to use this whenever referring to a list of state abbreviations.

Please be aware of this, and check any of your already-committed gcam-usa chunks for places where it should be used.

**Comment by kdorheim** [comment]
@bpbond I think the code all uses `gcamusa.STATES` where applicable. The documentation does not use `gcamusa.STATES` it usually says for all states in the USA. Do we care about that? Also I think sometimes `  repeat_add_columns(tibble(region = gcamusa.STATES)) %>%`
is used instead of `write_to_all_states` do we care about that?

**Comment by bpbond** [comment]
What documentation are we talking about?

Re using `repeat_add_columns` sure let's make that change if it produces same output. Thanks.

**Comment by kdorheim** [comment]
Just comments in the code. 

:ok_hand: to using `write_to_all_states` whenever possible.
