### ISSUE TITLE
CSV header parser

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#78]
We'd like metadata in CSV files to be parsed and attached, when possible, to data flowing into the data system.

E.g. a line with `Title: XXX` would get mapped to `add_title(parsed_string)`

Initially this would be optional, but it could be made obligatory (i.e. the parser would throw an error if no units specified) later.

See also #28

**Comment by bpbond** [comment]
@pkyle @ssmithClimate I have committed code that handles parsing of CSV file headers. Currently it's not enforced, but today @kvcalvin suggested (and I seconded) that we make at least `Title` and `Units` obligatory. Thoughts?

**Comment by rplzzz** [comment]
On a related note, what is our convention for specifying that a quantity is a pure number?  "Unitless"?  "NA"?  Something else? It actually came up in something else I'm working on, and I'm not sure what we usually do in those cases?

**Comment by rplzzz** [comment]
Back to the main topic, I'm a little behind, so I just caught up on the discussion at #28.  Might the [csvy](https://cran.r-project.org/web/packages/csvy/index.html) package provide a solution here?

**Comment by bpbond** [comment]
No convention at the moment. I've started a [wiki page](https://github.com/JGCRI/gcamdata/wiki/Input-files) on this; feel free to edit.

**Comment by bpbond** [comment]
csvy - yes, maybe. I looked at it and it wasn't immediately obvious how to bring in the header information as object attributes in the data system, so decided to roll my own solution (one that's fairly consistent with existing headers in the data system, when they exist) in commit 67c4f02. This could be revisited.

**Comment by rplzzz** [comment]
Yeah, on closer inspection, csvy isn't ready for prime time.  Trying to use `readr` as the engine fails on their example data sets, and writing seems to be locked to `write.table`, which is annoying.  It looks like the metadata gets brought in as attributes on the data frame and/or the columns, but the documentation for the package is not at all clear on a lot of things (for example, do all attributes get exported, or just certain ones?)

**Comment by bpbond** [comment]
@rplzzz . Agreed. If we want to switch in the future, after `csvy` has had time to mature, we should be able to write a script to auto-convert file headers.

**Comment by bpbond** [comment]
So - should `Title` and `Units` be required, at least, in every CSV file header? (Except for files downloaded from somewhere whose structure we want to preserve; those get dedicated chunks that will add documentation.) I'm all for it if people think it's worth the upfront cost.

**Comment by ssmithClimate** [comment]
I'm fine with Title and Units being required.

Doesn't look as if I can edit the wiki page - a few potential comments below:
"Be careful with editing in Excel" -> "Be careful with editing in Excel, commas in any line will break the text into two cells"

Should we add "Reference:" as a synonym for "Source:"?

The File attribute could be used by the parser to check if the name there is consistent with the actual filename, and throw a warning if not. (I like this because people often make new input csv's by copying existing ones -- this could be a check that they paid attention to updating the metadata appropriately).

**Comment by bpbond** [comment]
@ssmithClimate re wiki page - have you emailed me (*cough* as the instructions specified *cough*) and asked to be added to the `dsr` team?

`Reference` and `Source` can be synonyms, sure.

Re `File` - hmm. Seems super easy and, as you say, a good check that folks are paying attention.

**Comment by pkyle** [comment]
@bpbond Required Title and Units attributes could work--assuming we'll still be able to add other metadata (e.g., source), where applicable and available? Also assuming that title provides a description. However I'm not sure that requiring units is best, given the large number of files for which they don't apply. All mappings CSVs and most assumptions CSVs do not have units, either because the data read in are non-numeric, or because the numeric data are unitless (e.g., efficiencies/coefficients, share-weights, logit exponents, elasticiticies, and so on). I don't know, in the end I guess it doesn't matter as long as we're consistent on what strings to read in for this attribute; to @rplzzz 's point, it seems like both NA and unitless should be available options here. E.g., an elasticity is unitless, whereas the unit for a table that names regional markets is NA.

**Comment by bpbond** [comment]
But in that case, people can enter "unitless" or "NA" I think. We'll point people to the [relevant Wiki page](https://github.com/JGCRI/gcamdata/wiki/Input-Files).

OK, I think the path forward is pretty clear at this point and so will close the issue once the PR is in. Thanks!

**Comment by ssmithClimate** [comment]
Perhaps we want one more option for the Units field to indicate when there is a "Units" column in the table? Perhaps "units-in-table"? That would also be a way to deal with data with multiple units.

**Comment by bpbond** [comment]
That's fine, but I don't want any more code complexity at this point (no parsing table units for anything like that for now).
