### ISSUE TITLE
Can AGLU_HISTORICAL_YEARS be replaced with HISTORICAL_YEARS?

### ISSUE THREAD

**Issue by kdorheim** [JGCRI/gcamdata#861]
As part of constants clean up (#647) can AGLU_HISTORICAL_YEARS be replaced with HISTORICAL_YEARS?

**Comment by bpbond** [comment]
@pkyle ? They are identical numerically.

**Comment by pkyle** [comment]
The reason for AGLU_HISTORICAL_YEARS being a separate object is that several of the FAO databases tend to lag everything else by a few years. Most inventories are available two years after the given year, but some of the databases we use from FAOSTAT are 4 years. So, it will make an issue for updating the model calibration year, should we do that before ~2019.
In practice, the AGLU_HISTORICAL_YEARS have been the same as HISTORICAL_YEARS since about 2014, and since that time, I (and anyone else working on this) have not concerned myself with the distinction. So yes, it could be removed, and HISTORICAL_YEARS referenced in place, but just be aware that we might want to keep the ability for the ag data to have potentially different "historical years" than the other systems.

**Comment by bpbond** [comment]
Let's not for now, then. Let sleeping dogs lie and all that. Thanks!
