### ISSUE TITLE
Redoing L111.nonghg_en_R_S_T_Y

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#920]
@kdorheim and I have concluded that `L111.nonghg_en_R_S_T_Y` is, uh, problematic. It's been this way forever (see #610 and #613 ). Basically, it generates only two outputs but both fail tests at the slightest change. Some of this may be because of rounding issues (see #613 ) but it also is just poorly constructed, we suspect.

We think it's worthwhile to rebuild L111 from the ground up--have someone 'clean room' it, i.e. not look at the current code (which @kdorheim just disabled in #919 ) but rather redo it cleanly and completely. It's not long.

@rynacui @russellhz @crvernon Would any of you have a bit of time (I guess 4-8 hours) to do this?

**Comment by rynacui** [comment]
@bpbond Do we have a volunteer yet? I can take a look this week, but I'm not sure I still remember each single step...

**Comment by bpbond** [comment]
Hi Ryna, no, we don't. If you have some time, that would be hugely helpful. See Kalyn's note above about using the correct comparison data (@kdorheim is this already in `master`?). Thank you!

**Comment by ssmithClimate** [comment]
Part of the issue may be that methodology here is sharing out emissions data using multiple datasets across multiple data dimensions (sector, fuel, country). Small changes elsewhere seem likely to create some small numerical differences no matter how this is coded since there's so much sharing and dividing. Not sure how much re-coding will help that unless there some numerical precision being dropped somewhere along the line in the current code (not sure why that would happen if its all reals). 
(We've started the discussion of moving to calibrating with CEDS data, which is needed by a couple of other projects this year. That which won't require this sort of sharing out, so will be more robust and won't require anywhere near this much data manipulation.)

**Comment by bpbond** [comment]
Thanks for the insight, Steve.

**Comment by rynacui** [comment]
@kvcalvin @kdorheim Should I start working on this chunk? Just want to make sure no one else did.

**Comment by crvernon** [comment]
I have not started this one and will not have time to review it until later next week.   Thanks @rynacui !

@kvcalvin @kdorheim @bpbond

**Comment by kdorheim** [comment]
#928 adds the L111 comparison data. Do we have any takers for this chunk yet?

**Comment by rynacui** [comment]
@kdorheim yes, I'll start today.

**Comment by kdorheim** [comment]
@rynacui thank you!!! :pray:

**Comment by bpbond** [comment]
Addressed by #935
