### ISSUE TITLE
LoadFactor discrepancies in transportation_UCD_CORE.xml

### ISSUE THREAD

**Issue by kdorheim** [JGCRI/gcamdata#950]
### Problem: 

` transportation_UCD_CORE.xml` fails the python old new xml test because there are  three LoadFactor values that differ. In the python output below the left value refers to the old xml and the right value refers to values from the dsr xml. 

```
At: [('scenario', ''), ('world', ''), ('region', 'Southeast Asia'), ('supplysector', 'trn_freight_road'), ('tranSubsector', 'Truck (0-6t)'), ('stub-technology', 'Liquids'), ('period', '')]
	Left:
		loadFactor
		
		[]
		[]
		0.52
		
	Right:
		loadFactor
		
		[]
		[]
		0.53
		

At: [('scenario', ''), ('world', ''), ('region', 'Southeast Asia'), ('supplysector', 'trn_freight_road'), ('tranSubsector', 'Truck (0-6t)'), ('stub-technology', 'NG'), ('period', '')]
	Left:
		loadFactor
		
		[]
		[]
		0.52
		
	Right:
		loadFactor
		
		[]
		[]
		0.53
		

At: [('scenario', ''), ('world', ''), ('region', 'Southeast Asia'), ('supplysector', 'trn_freight_road'), ('tranSubsector', 'Truck (0-6t)'), ('stub-technology', 'NG'), ('period', '')]
	Left:
		loadFactor
		
		[]
		[]
		0.52
		
	Right:
		loadFactor
		
		[]
		[]
		0.53
		

At: [('scenario', ''), ('world', ''), ('region', 'Southeast Asia'), ('supplysector', 'trn_freight_road'), ('tranSubsector', 'Truck (0-6t)'), ('stub-technology', 'NG'), ('period', '')]
	Left:
		loadFactor
		
		[]
		[]
		0.52
		
	Right:
		loadFactor
		
		[]
		[]
		0.53
		
```

These values come from `L254.StubTranTechLoadFactor.csv` . When we compare the LoadFactor from dsr and the gcam5 comparison data we see that there are a total of 50 entries in  `Central America and Caribbean`, `South America_Northern`, ` EU-15`, `South America_Southern`, `Southeast Asia`, and `Mexico` have an absolute difference between gcam5 and dsr LoadFacotor greater than `0.01`. 

### Why: 
- The gcam 5 and dsr xmls contain different LoadFactor values because the `L254.StubTranTechLoadFactor` are different from one another. 
- This output is currently able to pass the old new tests because of  a `FALG_SUM_TEST` in `module_energy_L254.transportation_UCD`. When the `FLAG_SUM_TEST` is used the output fails the old new test.

**Comment by kdorheim** [comment]
@bpbond, @d3y419 do we care about a 0.01 difference LoadFactor values? If not then I suggest that we add an `OLD_DATA_SYSTEM_BEHAVIOR` block and leave in the `FLAG_SUM_TEST` in order to get the `L254.StubTranTechLoadFactor` to pass the old new test and `transportation_UCD_CORE.xm` to pass the xml test. 

If a difference of 0.01 in nontrivial then someone may need to take a look at `module_energy_L254.transportation_UCD` and will want to remove the `FLAG_SUM_TEST`. 

Also @rplzzz why is the `run-xml-tests.py` only picking up the 0.01 discrepancy in the Southeast Asia region?

**Comment by kdorheim** [comment]
@pkyle you may also be able to shed some light as to whether or not the 0.01 difference is something to be concerned about or ignore.

**Comment by rplzzz** [comment]
@kdorheim The difference report written to the output uses the sort keys of the nodes: https://github.com/JGCRI/gcamdata/blob/d4cbefc16b42844bd92b1f5cf671089643c3eed4/exec/xml_verify.py#L254-L258
The sort key is made up of normalized strings, in which floating point numbers are rounded to two significant figures:
https://github.com/JGCRI/gcamdata/blob/d4cbefc16b42844bd92b1f5cf671089643c3eed4/exec/xml_verify.py#L91-L114

However, when actually comparing elements the unrounded values are used.
https://github.com/JGCRI/gcamdata/blob/d4cbefc16b42844bd92b1f5cf671089643c3eed4/exec/xml_verify.py#L179-L184
Notice that what is actually passed to `num_equiv()` is `left.text` and `right.text`, which are the actual text values, not `lkey[4]` and `rkey[4]`, which are the rounded values.

Finally, the formula for numerical equivalence is:
https://github.com/JGCRI/gcamdata/blob/d4cbefc16b42844bd92b1f5cf671089643c3eed4/exec/xml_verify.py#L52-L56
With our settings, `ftol == 3e-3`, so with load factors around 0.5, values can differ by about 0.0015 and still be considered consistent.  If two numbers differ by that amount, but straddle the threshold for rounding, then they will pass, even though the rounded values differ.  Conversely, you could get values that differ by more than that amount, but still round to the same value.  Those will fail, despite being apparently equal in the rounded representation.

**Comment by pkyle** [comment]
The 0.01 difference in load factor is not significant as long as the read-in service demand quantities are calculated correctly, i.e. from the "new" load factor. The load factor is a part of the equation balancing the energy consumption (EJ/yr) inputs to transportation with the service demand outputs (passenger km, tonne-km). Both of these are calibrated. Going from 0.52 to 0.53 load factor, all else equal, will increase the service demand quantity produced by this technology by 2%. If there is an imbalance between the calibrated final service demand and the derived quantity from the energy, coefficient, and load factor, then (when the model is run) GCAM will increase the output of each technology within the given final demand as necessary to hit the read-in value for final demand. And if that causes energy demand to change beyond the calibration tolerance, then we fail calibration.

So there are two important things here: (1) consistency between the read-in energy consumption, coefficient, load factor, and service output; and (2) the same energy input quantity as before. The service demand quantity can be whatever as there are no further system interactions there.

FWIW my sense is this might be related to rounding, and when in the calculation sequence we perform the rounding. We could definitely have had an error in our current data set that just didn't cause model calibration problems because the changes stay within the calibration tolerance threshold.
